name = "Aether Automation"
author = "Nicklas"
version = "1.10.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "31cbe3f4647a95384c9e7f7f59e072ef54a8e126b732841ece4ffbf5da6ff8b2"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
