name = "Aether Automation"
author = "Nicklas"
version = "1.10.27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09641fce2bf907adb91946699ad5f6902748f881d4d42dc0e3d9d8a1ce90ce29"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
