name = "Aether Automation"
author = "Nicklas"
version = "1.10.29"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2de474bbc5e64523fb95283af1da0c274b936351847e6d41a97134be6fed8592"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.106"
